[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "accrediff"
version = "0.1.0"
description = "A coupled accretion–differentiation framework for terrestrial planet formation"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "Zhihui Kong", email = "kongzh0508@163.com" }
]

license = { file = "LICENSE" }

keywords = [
    "planet formation",
    "core-mantle differentiation",
    "N-body simulation",
    "geochemistry"
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3"
]

dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "pyyaml"
]


[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
    "build",
    "twine"
]
video = [
    "opencv-python",
    "natsort"
]
[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
accrediff = ["data/*"]